### ISSUE TITLE
Libgpiod cannot packageing a jni library

### ISSUE THREAD

**Issue by toni1727** [technexion-android/platform_external_libgpiod#1]
Good morning,

I integrated the external libgpiod.so(user-space IO) I extracted from the real board  into my Android app and called the APIs of libgpiod in JNI level.

So the function named gpiod_version_string() works well.

but all the rest APIs such as gpiod_ctxless_set_value(), gpiod_chip_open(), gpiod_chip_get_line() ... are possible to call in my Android app , but they do not work at all.

I think that can be your external library APIs have some errors while calling.

I put example code:

```
LOGI("GPIOd version is %s", gpiod_version_string());
const char *name = "gpiochip2";
int value = gpiod_ctxless_get_value((char *) name, 7, 0, "gpioget");
LOGD("GPIO value is %d", value);
gpiod_ctxless_set_value("/dev/gpiochip2", 7, 0, 0, "gpioset", NULL, NULL);
gpiod_chip *fd = gpiod_chip_open("/dev/gpiochip2");
if (fd != NULL) {
   LOGD("ROVER NOT NULL", "");
   gpiod_line *line = gpiod_chip_get_line(fd, 7);
   gpiod_line_set_value(line, 0);
} else {
    LOGD("ROVER NULL", "");
}
```

Could you check it out?

Best regards.

**Comment by wigcheng** [comment]
I always develop app using AOSP directly, not use android studio, but I think it's a bit difference only.
I write a demo app using your code as following repo:
https://github.com/technexion-android/packages_apps_GpiodJniTest

It can works fine, you can check you have include the libgpiod library or not, maybe you missing it.

In addition, the secure issue may another root cause if you access the gpio directly, you can issue commands on your target board via console debug to experiment:
chmod 777 /dev/gpiochip2
setenforce 0

Let me know if it works after issue these two commands, it means we need modify the AOSP to enable the permission.

Thanks and look forward your feedback.

**Comment by toni1727** [comment]
Thank you very much!

The issue was: 

chmod 777 /dev/gpiochip2
setenforce 0

It is necessary to call it after each reboot for the library to work.

Could you give me a stable solution?

Will the same happen with I2C, and UART?

Best regards.

**Comment by wigcheng** [comment]
UART is working (I tuned it before) but I2C should be got the same situation.
It's due to android system is care about the secure part especially the user control the hardware directly.

Of course I have solution but you have to compile our source code by yourself:
1. Quick way - disable selinux for all permission
Modify the source code path <source>/device/fsl/imx8m/pico_imx8mm/BoardConfig.mk
Add a parameter to BOARD_KERNEL_CMDLINE as following:
BOARD_KERNEL_CMDLINE := init=/init androidboot.hwrotation=90 androidboot.console=ttymxc1 androidboot.hardware=freescale cma=$(CMASIZE) androidboot.primary_display=imx-drm firmware_class.path=/vendor/firmware transparent_hugepage=never **androidboot.selinux=permissive**

Also need add gpiochip node permission to <source>/device/fsl/imx8m/pico_imx8mm/ueventd.freescale.rc
+/dev/gpiochip0            0666   system     system
+/dev/gpiochip1            0666   system     system
+/dev/gpiochip2            0666   system     system
+/dev/gpiochip3            0666   system     system
+/dev/gpiochip4            0666   system     system

Then compile it again, it will works.

2. Normal way is big effort such as selinux permission adding, maybe use quick way is enough, I can clear up the relative patches if you think it's necessary in the future.

Thanks

**Comment by toni1727** [comment]
Thank you very much, 

for I2C what file should be modified?

I will try to modify the files and inform you if I have any questions.

Best regards.

**Comment by wigcheng** [comment]
As I mention as above, it will disable all secure permission when add "androidboot.selinux=permissive" to boot arguments, of course include i2c devices.

But you need add 0666 permision to uevent file as above like this:
+/dev/i2c-0 0666 system system

It should be enough!
Sure, welcome to inform me.

**Comment by toni1727** [comment]
Thank you so much!

I have another issue.

When I try to release a GPIO pin defined in dts file. It doesnt work.

gpiochip2 -> Line 1 and Line 9

I don't use USB-C and any screen,  then I don't need them.

The only solution is to remove it from the dts file? Just removing them from the dts file is enough or is something else needed?

Thanks!

**Comment by wigcheng** [comment]
I don't understand what means "release a gpio" in dts but I guess you try to take out some exist definition from dts but not working, right? It's better if you post a specific part of dts.

it's enough if you just want to control the peripheral I/O, and if you want to use the pin which already occupied by dts, the only way is remove it from dts.

Thanks

**Comment by toni1727** [comment]
Thank you very much again, You are helping me a lot.
I have one last question (I hope)

It's about the pwm. I have tried to access with:

handle = open("/sys/class/pwm/pwmchip0/export", O_WRONLY);
rc = write(handle, value, 1);

but rc is always "-1"

I set the permissions:
chmod 777 /sys/class/pwm/pwmchip0/export

with no success.

What am I doing wrong?

Best regards.

**Comment by wigcheng** [comment]
It should be works, do you removed pwm for panel backlight from dts? 
path: arch/arm64/boot/dts/freescale/imx8mm-pico-pi.dts

If not, maybe it's due to pwm0 already be occupied by backlight, please remove it first.
Thanks

**Comment by toni1727** [comment]
The pwmchip0 was only an example. 

Happens the same with:
 
handle = open("/sys/class/pwm/pwmchip1/export", O_WRONLY);

I need PWM2_OUT 

Best regards.

**Comment by toni1727** [comment]
Ok with:
 
handle = open("/sys/class/pwm/pwmchip1/export", O_WRONLY);
rc = write(handle, value, 1);

it is ok, but when I try to open:

handle = open("/sys/class/pwm/pwmchip1/pwm0/enable", O_WRONLY);
rc = write(handle, value, 1);

return again -1

In the system there are not those files:

"/sys/class/pwm/pwmchip0/pwm0/enable"
"/sys/class/pwm/pwmchip0/pwm1/enable"
"/sys/class/pwm/pwmchip1/pwm0/enable"
"/sys/class/pwm/pwmchip1/pwm1/enable"

![image](https://user-images.githubusercontent.com/11811056/67845209-5e776c00-faff-11e9-94b5-cff72cffffa0.png)

is it normal?

I need PWM2_OUT

Best regards.

**Comment by wigcheng** [comment]
echo 0 > /sys/class/pwm/pwmchip1/export
It should be works, please try again, and note that  the permission issue, thanks

**Comment by toni1727** [comment]
chmod 777 /sys/class/pwm/pwmchip1/export
setenforce 0

handle = open("/sys/class/pwm/pwmchip1/export", O_WRONLY);
rc = write(handle, value, 1);
close(handle);

rc -> 1  -> OK! 

Then it appear:

![image](https://user-images.githubusercontent.com/11811056/67865523-ae6a2900-fb27-11e9-96f4-7505f7e5f292.png)

The next step that I do:

handle = open("/sys/class/pwm/pwmchip1/pwm0/enable", O_WRONLY);
rc = write(handle, value, 1);
close(handle);
rc -> -1  -> ERROR!  (ALWAYS)

I have not rights!

How can I created pwm0 with all rights?

**Comment by toni1727** [comment]
> chmod 777 /sys/class/pwm/pwmchip1/export
> setenforce 0
> 
> handle = open("/sys/class/pwm/pwmchip1/export", O_WRONLY);
> rc = write(handle, value, 1);
> close(handle);
> 
> rc -> 1 -> OK!
> 
> Then it appear:
> 
> ![image](https://user-images.githubusercontent.com/11811056/67865523-ae6a2900-fb27-11e9-96f4-7505f7e5f292.png)
> 
> The next step that I do:
> 
> handle = open("/sys/class/pwm/pwmchip1/pwm0/enable", O_WRONLY);
> rc = write(handle, value, 1);
> close(handle);
> rc -> -1 -> ERROR! (ALWAYS)
> 
> I have not rights!
> 
> How can I created pwm0 with all rights?

Even if I change the permissions "on the fly" it still not working

![image](https://user-images.githubusercontent.com/11811056/67875570-d1500980-fb36-11e9-8157-af9021badebb.png)


//pwm_open_device
int handle = open("/sys/class/pwm/pwmchip1/export", O_WRONLY);
int rc = write(handle, "0", 1);
close(handle);

//pwm_enable

int handle = open("/sys/class/pwm/pwmchip1/pwm0/enable", O_WRONLY);
int rc = write(handle, "1", 1);  **(ALWAYS FAILS)**
close(handle);

//pwm_close_device

int handle = open("/sys/class/pwm/pwmchip1/unexport", O_WRONLY);
int rc = write(handle, "0", 1);
close(handle);
